get:
    tags:
        - Schema
    summary: Get schema
    operationId: getSchema
    responses:
        "200":
            description: Success
            content:
                application/json:
                    schema: ~
                application/ld+json:
                    schema: ~
